# Site settings
title: Burnian's Blog
description: Burnian Zhou's Personal Blog Site
url: "https://burnian.github.io"  # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
# permalink: /:categories/:title/


# User settings
user_name: Burnian Zhou
user_desc: I'm a nomad Indie Game Developer, always searching for the next challenge and beauty.
user_title: Indie Game Developer
email: burnian@163.com
jekyll: https://jekyllrb.com
github: https://github.com/burnian
# Publish posts or collection documents with a future date.
future: false
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge


# markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# markdown: kramdown
# kramdown:
#   input: GFM                            # use Github Flavored Markdown !important
#   syntax_highlighter_opts:
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1


# markdown text formats
indent: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"


# Build settings
# comment plugin
gitalk:
  enable: true
  owner: Nick
  repo: nicktcl.github.io

paginate: 5
paginate_path: "/pages/blog:num/"

collections:
  authors:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-paginate


# Analytics settings
# Baidu Analytics
# ba_track_id: [ba_track_id]

# Google Analytics
ga_track_id: 'UA-134814157-1'            # Format: UA-xxxxxx-xx
ga_domain: auto


# MathJax rendering for layout:page, used to render math fomula.
page-mathjax: false


# friend's link
friends: [
  {
    title: "一笑清寒",
    href: "http://www.piqiandong.com/"
  }
]
